baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-cards"
paginate = 6

[params]
  builtBy = "bool"
  defaultImage = "default.jpg"

  facebook = ""
  quora = ""
  twitter = "http://twitter.com/bul_ikana"
  github = "http://github.com/bul-ikana"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  custom_css = ["css/custom.css"]

  [params.copyright]
     name = "bool"
     link = "https://bool.netlify.com"
